spring.application.name=Booking-Management-API

spring.datasource.username=postgres
spring.datasource.password=sadiqqidas777
spring.datasource.url=jdbc:postgresql://localhost:5432/final_project

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:liquibase/changelog-master.yaml
spring.liquibase.enabled=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sadiq242777@gmail.com
spring.mail.password=kxud edji ueqz ruld
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


subscription.size = 100
subscription.page = 0

jwt.access-expiration-minutes=15
jwt.refresh-expiration-days=30


percent10 = 10
percent20 = 20
percent30 = 30
percent50 = 50
percent70 = 70


adultPrice = 50
childPrice = 25