spring.application.name=Booking-Management-API

spring.datasource.username=postgres
spring.datasource.password=sadiqqidas777
spring.datasource.url=jdbc:postgresql://localhost:5432/final_project

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:liquibase/changelog-master.yaml
spring.liquibase.enabled=true

#logging.level.root=debug

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sadiq242777@gmail.com
spring.mail.password=kxud edji ueqz ruld
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


subscription.size = 100
subscription.page = 0

jwt.secret=SADIG_SECRET_KEY_FOR_TEST_PROJECT_IN_MATRIX
jwt.access-expiration-minutes=15
jwt.refresh-expiration-days=7

percent10 = 10
percent20 = 20
percent30 = 30
percent50 = 50
percent70 = 70


currency.usd-to-azn=1.7
currency.usd-to-try=43
currency.usd-to-rub=80
currency.eur-to-usd=1.14



loyalty.earning-rate=0.05
loyalty.point-value=0.01

booking.children.infant-max-age=2
booking.children.infant-discount-percent=100

booking.children.young-max-age=9
booking.children.young-discount-percent=50

booking.children.teen-max-age=13
booking.children.teen-discount-percent=40